# Generated by Django 2.2.2 on 2019-06-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asd_rest_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='LANDED', max_length=100)),
                ('area_id', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
